version: '3.7'

services: 
  frontend:
    image: michaelacook1/frontend:fe
    build: ./frontend/.
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    image: michaelacook1/backend:be
    build: ./backend/.
    ports:
    - target: 5001
      protocol: tcp
